### ISSUE TITLE
Edit sales button is floating when there are multiple entries

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#10]
### Description
- After multiple entries to the table, edit sales is still seen in the screen

### Steps to Reproduce:
1. Go to home page
2. Create many entries to be able to scroll down and up the page

### Expected Results:
- Edit sales remains intact to its original spot

### Actual Results:
- Edit sales is floating at the same spot of the screen

### Screenshots
![image](https://user-images.githubusercontent.com/60463265/148639354-418d0808-1f75-492c-87e2-f243f55eb6f6.png)

**Comment by wappints** [comment]
fixed.
