### ISSUE TITLE
Balance Page Bugs

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#11]
### Description
- Editing customer transaction that makes the balance 0 and then modifying amount paid to change balance to be greater than 0 removes the customer details on the balance page (see screenshots 1)
- Additional: If you edit the entry to have balance back to 0, the entry is still present in the balance page. (see screenshot 2)
- This bug is also prevalent when you edit a customer sale entry from balance=0 to balance>0 by editing the things bought (see screenshots 3)

### Steps to Reproduce:
1. Go to home page
2. Input a sale with name or phone number
3. Check balance page to see the corresponding entry 
3. Enable edit sales
4. Edit amount paid to be equal to balance
5. Edit amount paid to make balance greater than 0
6. Go to balance page

### Expected Results:
- Balance page should retain information about customer

### Actual Results:
- Balance entry was not able to retain information about the customer edited

### Screenshot 1
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60463265/148674809-473aad98-a078-408e-b90a-e5790c6b27bc.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60463265/148674821-6831415c-4bb8-4d73-8cc9-d844d434180f.png">

### Screenshots 2
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60463265/148675167-7eabd0d9-20b7-4ad2-aeaf-5f35878bd1d1.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60463265/148675185-94f5da0a-de75-4fb3-9b8c-17ddc78b6d1c.png">

### Screenshots 3
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60463265/148675315-1da2bd54-2962-4efd-8946-37ff6f02bce4.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60463265/148675296-d188129f-7c5e-455b-95c2-2c471ab1b8ef.png">

**Comment by wappints** [comment]
Fixed
