### ISSUE TITLE
Program crash when editing sale by spamming numbers or by entering a letter

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#12]
### Description
- Program crashes when inputs are "spammed" in the customer transaction input fields

### Steps to Reproduce: (look at screenshots for better view of steps)
1. Go to home page
2. Add sale with amount paid == total price
3. Click confirm
4. Enable edit sales
5. Edit a field that makes total price lower than amount paid (expect the amount paid to adjust to be equal to the total price)
6. Enter "123" in a rapid manner (or characters in the same manner) on the amount paid field or total price field

### Expected Results:
- Program does not crash

### Actual Results:
- Program crashes

### Comment:
- I'm guessing that it crashes because it cannot keep up with deleting the document everytime the data is invalid
<img width="587" alt="image" src="https://user-images.githubusercontent.com/60463265/148677126-6f3edc21-7f9d-4f68-820e-06ce3458660f.png">

### Screenshots 
![image](https://user-images.githubusercontent.com/60463265/148677057-a6026816-f6ca-4c66-943e-c1a0c32aa350.png)
![image](https://user-images.githubusercontent.com/60463265/148677063-5dc48d86-3a74-45a7-b678-a2a1d0f78b51.png)
![image](https://user-images.githubusercontent.com/60463265/148677067-26e552e3-86f9-4b14-9440-fb6419e08946.png)

**Comment by wappints** [comment]
Fixed
