### ISSUE TITLE
Reminder to press enter key is displayed when selecting either name or phone field in home page

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#13]
### Description
- Reminder is displayed when user presses anything on the keyboard when name or phone field is selected
- Additional bug: when selecting fields with no name or phone number, field becomes blank even if edit sales is disabled

### Steps to Reproduce:
1. Go to home page 
2. Create sale
3. Select any field in either name or phone number field
4. Don't enable edit
5. press anything on keyboard

### Expected Results:
- No kind of message is displayed

### Actual Results:
- Reminder is displayed

### Screenshots 
![image](https://user-images.githubusercontent.com/60463265/148685666-6d70b63b-8db2-4c4d-b2e1-e588b77a3f49.png)

![image](https://user-images.githubusercontent.com/60463265/148686032-fa310b16-7e6a-451e-b505-b9e1fe64d581.png)

**Comment by wappints** [comment]
fixed
