### ISSUE TITLE
Can enter payment greater than remaining balance in Balance Page

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#14]
### Description
- Both users can enter a payment greater than the remaining balance

### Steps to Reproduce:
1. Go to home page and enter a sale with balance > 0
2. Go to balance page 
3. Select field and enter payment greater than balance displayed

### Expected Results:
- Payment will not be greater than balance 

### Actual Results:
- Can enter payment without balance but the actual payment that gets processed is not greater than balance

### Screenshots

**Comment by wappints** [comment]
fixed
