### ISSUE TITLE
Account Management Bugs

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#15]
### Description
- Admin has the ability of creating user accounts that have no values and also have accidental inputs that an be hard to trace on a user level (if incase a leading space was inputted when creating or editing a user)

### Steps to Reproduce:
1. Log in as admin
2. Go to Account > Management

### Expected Results:
- [x] Leading spaces should not be accounted
- [x] Add employee should not accept leading lines
- [x] Editing employee name should retain old password
- [x]  Editing password should retain old employee name

### Other Recommendations:
- [x] Confirm button should not be clickable if name or password fields are empty. Both should have value before confirm button is enabled (both for admin and employee)
- [x] I think there should be a checker for possible duplicate accounts? If employee name was edited to a user that already exists then it will show an error message or a warning?
- [x] Names should be `camel cased` as in William Dimaculangan, in the front-end (see 5th  and 6th screenshot) since admin can remove the camel case thingy when editing the employee name

### Actual Results:
- See screenshots

### Screenshots 
![image](https://user-images.githubusercontent.com/60463265/149293422-60c0374c-d697-4e73-8980-74c891c91b1c.png)
![image](https://user-images.githubusercontent.com/60463265/149292444-c12db086-e37b-4f01-9c8b-07ff86c8718e.png)
![image](https://user-images.githubusercontent.com/60463265/149292496-e05f8fd2-5099-4ed7-ba00-22c0ea09eddb.png)
![image](https://user-images.githubusercontent.com/60463265/149292504-bb5d2d1d-1905-434b-bb91-82bb67ccdc36.png)
![image](https://user-images.githubusercontent.com/60463265/149294577-683e636a-d252-419e-a239-412b4cafe91f.png)
![image](https://user-images.githubusercontent.com/60463265/149294683-4caf0954-9947-48da-a2a0-1d9750dfe7f5.png)

**Comment by wappints** [comment]
fixed
