### ISSUE TITLE
Deleting account bug

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#16]
### Description
- Deleting one account leads to deleting multiple accounts

### Steps to Reproduce:
1. Login as admin
2. Go to account management 
3. Employee list should be more than 1
4. (Look at screenshots for a more visual step) > click trash button for first element (william1) and click cancel > click trash button for second element (william2) and click confirm

### Expected Results:
- Only william2 gets deleted

### Actual Results:
- william1 and william2 gets deleted

### Screenshots 
![image](https://user-images.githubusercontent.com/60463265/149296226-fc4167df-82a6-4c88-9421-81a1dfa4ffa2.png)
![image](https://user-images.githubusercontent.com/60463265/149296626-71d63aa3-da45-42bc-b192-2780d823c7ba.png)

**Comment by wappints** [comment]
fixed
