### ISSUE TITLE
Changing Name of Admin Crashes Program

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#17]
### Description
- Editing name of admin crashes program in account management

### Steps to Reproduce:
1. Login to system as admin
2. Go to account management
3. Edit admin name field to preferred name
4. Click confirm

### Expected Results:
- Program does not crash

### Actual Results:
- Program crashes see screenshot for reference

### Screenshots 
![image](https://user-images.githubusercontent.com/60463265/151116278-41952e3b-2636-4c23-aa87-28d946d9b55a.png)

**Comment by wappints** [comment]
fixed
