### ISSUE TITLE
Editing admin does not display error

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#18]
### Description
- Pressing confirm when editing admin information does not display error if fields are empty

### Steps to Reproduce:
1. Login as admin and go into management page
2. Click edit and confirm

### Expected Results:
- Shows error

### Actual Results:
- No error is shown

### Screenshots 
![image](https://user-images.githubusercontent.com/60463265/151137820-98405375-5378-446c-a76f-31e81213fb52.png)
![image](https://user-images.githubusercontent.com/60463265/151137603-1c927d21-0f8f-45b7-8275-46e39b890140.png)

**Comment by wappints** [comment]
fixed
