### ISSUE TITLE
Spamming confirm button in account creation freezes program 

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#19]
### Description
- When admin spams the confirm button on account creation when a user already exists 

### Steps to Reproduce:
1. Login as admin and login session
2. Go to management page and suppose there is an account with name "emp two" (check screenshot one)
3. Try to create account that already exists (check screenshot two)
4. Spam confirm button 10 times 
5. Change employee name to something that does not exist yet (check screenshot 3)
6. Press confirm

### Expected Results:
- Application does not hang

### Actual Results:
- Error still shows up despite user not existing
- it does not accept any input even if employee name doesn't exist in the db
- Even if you close the window you cannot navigate to other systems

### Possible solution
- Disable confirm button as it loads, then reenable after it checks the db. My guess is that the db process could not keep up with the spam
### Screenshots 
![image](https://user-images.githubusercontent.com/60463265/151337200-ddad8036-b8f7-49ca-a622-ace7638df169.png)
![image](https://user-images.githubusercontent.com/60463265/151337274-8985f549-bea0-4bba-a4bf-a396fd1a8b9c.png)
![image](https://user-images.githubusercontent.com/60463265/151337212-df6fa54a-8e4b-47da-a162-0acc0b4046f7.png)

**Comment by wappints** [comment]
fixed
