### ISSUE TITLE
Log in session still displays 

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#5]
### Description
- Logging in with correct credentials displays an error message briefly as the user is brought to the home page

### Steps to Reproduce:
1. Log in as either employee or admin
2. Enter correct credentials
3. Expect to see error message at a brief time

### Expected Results:
- No error message is displayed

### Actual Results:
- Error message is displayed

### Screenshots 
![image](https://user-images.githubusercontent.com/60463265/148317402-ff613a5d-d528-49c6-bdf7-dd59971fc88a.png)

**Comment by wappints** [comment]
fixed

**Comment by dot-william** [comment]
Hello, 

### Steps to Reproduce:
1. Log in as william dimaculangan and enter correct credentials
2. Change session to Jayzel Delfin and enter correct credentials

### Expected Results:
- No error message is displayed

### Actual Results:
- Error message is displayed briefly
