### ISSUE TITLE
Error Messages not Clearing on Add sales

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#6]
### Description
- Error messages do not clear up when there is an error in the fields on add sales when the window is closed

### Steps to Reproduce:
1. Click add sales
2. Click confirm
3. Close window
4. Click add sales again

### Expected Results:
- Displayed error should not be present

### Actual Results:
- Error is still displayed, as well as amount paid (see first screenshot)

### Screenshots 
![image](https://user-images.githubusercontent.com/60463265/148341534-3f1aa1fe-e277-4c2a-a0ec-3fe5dab6440d.png)

**Comment by wappints** [comment]
Fixed.
