### ISSUE TITLE
Accessibility Issue

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#7]
- The dialog box is quite unusable at certain screen sizes. It would be best if the dialog box is dynamic to screen size of the user (see screenshot 1)
- Edit button is not aligned when the application is windowed (see screenshot 2)

### Screenshot 1 (possible solution: https://stackoverflow.com/questions/10476632/how-to-scroll-the-page-when-a-modal-dialog-is-longer-than-the-screen)
![image](https://user-images.githubusercontent.com/60463265/148637358-4fd1174a-3133-4587-aaee-5a5f75dfe7ad.png)

### Screenshot 2
![image](https://user-images.githubusercontent.com/60463265/148637492-d4ce9883-da3e-494f-b843-7bee4ea17976.png)

**Comment by wappints** [comment]
both fixed
(1st - modal made scrollable)
(2nd - automatically fixed from the other issue)
