### ISSUE TITLE
Reminder and warning are being displayed at the same time in an unorganized manner

### ISSUE THREAD

**Issue by dot-william** [wappints/CSSWENGFinal-Group3#8]
### Description
- The reminder that pops up to remind the user to press the ENTER key when name and phone fields are being edited 'destroys' the look of the app
 
### Steps to Reproduce:
1. Go to home page
2. Remove both name and phone number at a certain field

### Expected Results:
- Something that looks nicer, any solution will do as long as it looks more "pleasing" to the eyes haha

### Actual Results:
- See screenshot

### Screenshot
![image](https://user-images.githubusercontent.com/60463265/148637889-86156ed0-3328-4005-abda-0a7e4efb72a3.png)

**Comment by wappints** [comment]
fixed. (one message at a time will show up).
